### ISSUE TITLE
Itch.io macOS version missing executable flag

### ISSUE THREAD

**Issue by Ecostack** [mlange-42/tiny-world#182]
The `tiny-world-macos-amd64` executable on itch.io does not have the executable flag.
A `chmod u+x tiny-world-macos-amd64` should help here.

There is also an `arm64` version, can that be uploaded too?

**Comment by mlange-42** [comment]
`chmod` stuff should be possible in the CI, right?

For the upload, yes, it was just [this weird folder thing](https://github.com/mlange-42/tiny-world/pull/165#issuecomment-1989259263) why I did not in the first place.

**Comment by Ecostack** [comment]
Maybe you can upload the new `.app` file I proposed in the PR. 
You can see the files here: https://github.com/Ecostack/tiny-world/releases/tag/macOS-build

**Comment by mlange-42** [comment]
The thing is that the game developed a lot over the past days, and I want to release all that new stuff bundled, maybe accompanied by a devlog post. Probably within the next week or so.

To keep the downloadables in sync, I would suggest to either wait for the release, or to make a build from v0.1.0 (preferrably using a branch and letting the CI do the job) for upload.
