### ISSUE TITLE
Change key layout for game speed

### ISSUE THREAD

**Issue by Ecostack** [mlange-42/tiny-world#208]
The buttons for page up and page down might not be available on laptop keyboards. It maybe can be considered to place those on other keys, such as `[` and `]`.

**Comment by mlange-42** [comment]
Yeah, that would be an option. Should, however, not be implemented using `inpututil.IsKeyPressed`, but using `ebiten.AppendInputChars`.

**Comment by mlange-42** [comment]
🤔 Shouldn't PgUp/PgDown always ne there? Maybe only accessible using `Fn` key or so, but I can't remember having seen a laptop completely missing those keys.

**Comment by Ecostack** [comment]
Turns out that on MacBooks `Fn + ArrowUp/ArrowDown` is `PgUp/PgDown`. That works.

My external keyboard is making issues though. The function key combination is not working.
https://www.logitech.com/en-us/products/keyboards/k380-multi-device.920-009600.html

Maybe keeping `PgUp/PgDown` is fine but it can cause issues.
