### ISSUE TITLE
Question regarding watermill and windmill road connection

### ISSUE THREAD

**Issue by Ecostack** [mlange-42/tiny-world#212]
Should the road of the watermill and windmill lead back to the main house, before their properties like population increase are added?
It seems, just adding 1 piece of road already activates their feature.

<img width="1702" alt="Screenshot 2024-03-14 at 22 45 34" src="https://github.com/mlange-42/tiny-world/assets/8505607/c456dab3-59d1-4c26-8193-e79d720ae4e7">

**Comment by mlange-42** [comment]
For the population effect, simple road access is sufficient. However, mills are also a drop-off point for food, so you may still want a real road connetion.

However, this is definitely a field for potential improvements. See #124.

**Comment by Ecostack** [comment]
In that case, this one can be closed.
