### ISSUE TITLE
Monastery generates infinite food

### ISSUE THREAD

**Issue by vitr** [mlange-42/tiny-world#265]
Is it by design or a bug? As soon as I place it, the food storage goes to the limit and never ends
![image](https://github.com/mlange-42/tiny-world/assets/2770290/31d63651-670b-4a41-a4b2-4fc3d0e8201c)

**Comment by mlange-42** [comment]
Thanks @vitr for reporting. As your food production is way below the consumption, it looks like a bug. Will look into it.

**Comment by mlange-42** [comment]
Fixed in #266. Thanks again!
