### ISSUE TITLE
Make borders of the world visible

### ISSUE THREAD

**Issue by hnolzen** [mlange-42/tiny-world#63]
It would be helpful if the player could visualise the borders of the world within which he or she can place the land use (grass, water, desert). For example, with a shortcut to switch the borders on and off. Then the player could plan the design of the world better and would not spontaneously encounter invisible borders.

**Comment by mlange-42** [comment]
If the world remains limited as at the moment, this would be a good feature.

Alternatively, the world could also be inifinte of just very vast.

**Comment by hnolzen** [comment]
Great, thank you!

**Comment by mlange-42** [comment]
Closing as solved. Feel free to re-open in case this is still an issue.
