### ISSUE TITLE
Tooltip sometimes freezes

### ISSUE THREAD

**Issue by hnolzen** [mlange-42/tiny-world#75]
If you hover over the items in the sidebar with the cursor, the tooltip sometimes does not go away and freezes, even if you then select and build other items. This happened repeatedly and after several restarts of the game.

**Comment by mlange-42** [comment]
@hnolzen Thank you for reporting! I will have an eye on it.

In case you find a way to reproduce the issue, please report! Thanks!

**Comment by mlange-42** [comment]
This can be reproduced by using a shortkey to remove a button with tooltip visible.
